### ISSUE TITLE
openlayers popup not displaying calculated area

### ISSUE THREAD

**Issue by blackundertone** [farmOS-legacy/farm_area#1]
I wasnt sure where to log this as I dont have a Drupal account to log the issue there.

I installed farmOS 7.x-1.0-beta12 under a subdirectory on my LAMP server and it appears for some reason that the URL format is different on this install vs the demo I spun up on https://simplytest.me/ - and on my instance, the areas are not showing.

My Instance: http://<server>/path/?q=farm/areas
        [http://farmos/farmos/?q=farm/areas]

Simplytest.me instance: https://<server>/farm/areas
        [https://drtnp.ply.st/farm/areas]

I believe I have tracked it down to this javascript module.

```
   farm_area/js/farm_area.openlayers.popup.js 
```

When I click on an area, it calls: http://farmos/farmos/?q=farm/area/paddock.

It correctly populates [ol-popup-name]

However when it calls to get the area details to populate [ol-popup-description], it gets a 404 as it the request doesnt include the /?q=

```
   http://farmos/farmos/farm/area/26/details [HTTP/1.1 404 Not Found]
```

If I manually edit & re-submit that request, including the /?q= I can see the response data correctly provides the calculated area.

```
   http://farmos/farmos/?q=farm/area/26/details
```

"\u003Cp\u003E\u003Csmall\u003ECalculated area: 122.26 acres\u003C\/small\u003E\u003C\/p\u003E"
# 

Request made by clicking on the area, which brings up the popup window. The Area Name is displayed, just not the calculated area.

REQUEST:

GET /farmos/farm/area/26/details HTTP/1.1
Host: farmos
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: application/json, text/javascript, _/_; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://farmos/farmos/?q=farm/areas
Cookie: Drupal.tableDrag.showWeight=0; has_js=1; SESSee42cfb3ee4573e8c9fea527d1623740=qs2LR7H8nMfl8TOUE4DbeL6LNz5cSgyVP3ENUv-2FFY; SESSf256e7e17a7c37d066ab254fdc6bafa1=frvaG8qbuPhsJGXu6uleh92HKXiFCVunElLRhl50Ipg; DrupalModuleFilter=activeTab%3Dopenlayers
Connection: keep-alive

RESPONSE HEADERS:

HTTP/1.1 404 Not Found
Date: Thu, 28 Jul 2016 14:17:50 GMT
Server: Apache/2.4.7 (Ubuntu)
Content-Length: 296
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
# Content-Type: text/html; charset=iso-8859-1
# 

Manually changing the GET request to include ?q=

REQUEST:

GET /farmos/?q=farm/area/26/details HTTP/1.1
Host: farmos
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: application/json, text/javascript, _/_; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://farmos/farmos/?q=farm/areas
Cookie: Drupal.tableDrag.showWeight=0; has_js=1; SESSee42cfb3ee4573e8c9fea527d1623740=qs2LR7H8nMfl8TOUE4DbeL6LNz5cSgyVP3ENUv-2FFY; SESSf256e7e17a7c37d066ab254fdc6bafa1=frvaG8qbuPhsJGXu6uleh92HKXiFCVunElLRhl50Ipg; DrupalModuleFilter=activeTab%3Dopenlayers
Connection: keep-alive

RESPONSE HEADERS:

HTTP/1.1 200 OK
Date: Thu, 28 Jul 2016 14:23:10 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.17
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: no-store
x-content-type-options: nosniff
Content-Length: 95
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json

RESPONSE:
# "\u003Cp\u003E\u003Csmall\u003ECalculated area: 122.26 acres\u003C\/small\u003E\u003C\/p\u003E"

Cheers,
Ash

**Comment by blackundertone** [comment]
Just wanted to update this - I modified the file /profiles/farm/modules/farm/farm_area/farm_area.openlayers.popup.js

REPLACED:  jQuery.getJSON(Drupal.settings.basePath + 'farm/area/' + area_id + '/details', function(data) {

WITH:  jQuery.getJSON(Drupal.settings.basePath + '?q=farm/area/' + area_id + '/details', function(data) {

And it now works for me. I click on the area & submits the correct request (http://farmos/farmos/?q=farm/area/26/details) and it now displays the Calculated Area properly [Calculated area: 122.26 acres]

Not sure if this is unique to my install under a subdirectory or not ?

**Comment by mstenta** [comment]
Hi @blackundertone - thanks for reporting this. Based on your information, here's what I think is happening:

First, it seems that "Clean URLs" is not currently enabled in your site. That's why you see all your paths starting with "?q=".  With clean URLs enabled, the "?q=" is automatically re-written by the web server so that it does not appear.

This is usually a result of web server configuration. The Drupal.org page on clean URLs should help you to debug that: https://www.drupal.org/getting-started/clean-urls

Secondly, though, this does demonstrate a bug in farmOS. Namely, that the Javascript for the area popups are assuming that clean URLs is enabled. Ideally, that script would work whether or not clean URLs is enabled... I will create a bug report for that and make a fix for the next release. Thanks again for reporting it!

**Comment by mstenta** [comment]
Here's the bug report I created, referring back to this issue: https://www.drupal.org/node/2774957

**Comment by blackundertone** [comment]
Hi Michael,

Thanks for such a quick response, I will check clean urls settings in
Drupal and then change back the js as suggested. I'm brand new to Drupal
(only run it for FarmOS). I will be sure to update once I've confirmed that
fixes my problem.

Thank you on behalf of farmers across the globe (I'm in Australia) for the
time, energy & quality project you work on. I look forward to working with
this to manage beef cattle production across multiple properties.

Cheers,
Ash

**Comment by mstenta** [comment]
Hi Ash, thanks for the kind words and encouragement! They mean a lot! :+1: 

If you are interested, I'm compiling a list of farms that are using farmOS. Would you like to be included? I started an issue in the documentation project to start collecting farm names: https://github.com/farmOS/documentation/issues/12

Good luck with farmOS! Hopefully it is helpful to you! And feel free to submit ideas! :-)

**Comment by blackundertone** [comment]
Hey Michael,

Just wanted to provide an update to close out this one, I enabled
clean-urls, reverted the mod I made to farm_area.openlayers.popup.js and
its happily working as built.

Cheers,
Ash
