### ISSUE TITLE
No map in Farm Areas - Geometry

### ISSUE THREAD

**Issue by ytiruces** [farmOS-legacy/farm_area#3]
Hello!

This http://farmos.org/hosting/googlemaps/ instruction done, but I still have no map in geometry. There is a blank panel.

What did I miss?

**Comment by mstenta** [comment]
Do you see any errors in the browser console? Right click in the page somewhere (not in the map) and click "Inspect", then click on the "Console" tab. Please copy and paste anything in that tab to this issue.

**Comment by ytiruces** [comment]
Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at pinchzoom.js:1
group.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at group.js:1
mousewheelzoom.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at mousewheelzoom.js:1
dragpan.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at dragpan.js:1
doubleclickzoom.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at doubleclickzoom.js:1
GeolocateControl.js:7 Uncaught ReferenceError: ol is not defined
    at GeolocateControl.js:7
geolocate.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at geolocate.js:1
layerswitcher.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at layerswitcher.js:1
ol3-layerswitcher.js:9 Uncaught ReferenceError: ol is not defined
    at ol3-layerswitcher.js:9
scaleline.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at scaleline.js:1
zoom.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at zoom.js:1
progressbar.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at progressbar.js:1
zoomtosource.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at zoomtosource.js:1
geofieldControl.js:1 Uncaught ReferenceError: ol is not defined
    at geofieldControl.js:1
geofield.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at geofield.js:1
tilewms.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at tilewms.js:1
vector.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at vector.js:1
GeofieldWidget.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at GeofieldWidget.js:1
googlemaps.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at googlemaps.js:1
olmap.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at olmap.js:1
Circle.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at Circle.js:1
inlineJS.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at inlineJS.js:1
vector.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at vector.js:1
geojson.js?ouqdp7:166 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at geojson.js?ouqdp7:166
tile.js:1 Uncaught TypeError: Cannot read property 'pluginManager' of undefined
    at tile.js:1

**Comment by ytiruces** [comment]
Restart server and clear cache not helping.

**Comment by mstenta** [comment]
Thanks - Hmm, it sounds to me like the Openlayers library is not loading.

What version of farmOS are you using?

Try turning on the Openlayers UI module (via /admin/modules) and go to /admin/structure/openlayers. Under "Library loading configuration", it should say "ol3 3.11.2" (using CDNJS). Is that what it's set to on yours?

**Comment by ytiruces** [comment]
Another installation is ok. I think it was something on proxy side.
